// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeCPc7bZoCGQEwRRzA5T5uPau1GMzGBZs',
    appId: '1:36210284808:web:0cba1f0eb001f847f934bd',
    messagingSenderId: '36210284808',
    projectId: 'ct-shopping-list-challenge',
    authDomain: 'ct-shopping-list-challenge.firebaseapp.com',
    storageBucket: 'ct-shopping-list-challenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2po5GqsiLwM5oWU9oyI_kfOL6OzUb3mo',
    appId: '1:36210284808:android:c836b5b58d75879ff934bd',
    messagingSenderId: '36210284808',
    projectId: 'ct-shopping-list-challenge',
    storageBucket: 'ct-shopping-list-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeAixzvre6Zf9IWQC0QaIkjzKM4fEZXGI',
    appId: '1:36210284808:ios:76e6d6ccab34d573f934bd',
    messagingSenderId: '36210284808',
    projectId: 'ct-shopping-list-challenge',
    storageBucket: 'ct-shopping-list-challenge.appspot.com',
    iosClientId: '36210284808-5f5jvla9vou3qfk6tsqnt7mv4168a2s3.apps.googleusercontent.com',
    iosBundleId: 'com.luisredondo.ctShoppingListChallenge',
  );
}
